#!/bin/bash

ec2_servers=( \
"ec2-54-174-6-90.compute-1.amazonaws.com" \
"ec2-54-149-9-25.us-west-2.compute.amazonaws.com" \
"ec2-54-67-86-61.us-west-1.compute.amazonaws.com" \
"ec2-54-72-167-104.eu-west-1.compute.amazonaws.com" \
"ec2-54-93-182-67.eu-central-1.compute.amazonaws.com" \
"ec2-54-169-146-226.ap-southeast-1.compute.amazonaws.com" \
"ec2-54-65-104-220.ap-northeast-1.compute.amazonaws.com" \
"ec2-54-66-212-131.ap-southeast-2.compute.amazonaws.com" \
"ec2-54-94-156-232.sa-east-1.compute.amazonaws.com" )

if [ $# -lt 10 ] || [ "$1" != "-p" ] || [ "$3" != "-o" ] || [ "$5" != "-n" ] || [ "$7" != "-u" ] || [ "$9" != "-i" ]
then
	echo "Usage is:"
      	echo "./stopCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
fi

port=$2
origin=$4
name=$6
username=$8
keyfile=${10}
http_path=$(pwd) 

exist_port=`ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu  "ps acux | grep $username | grep dnsserver | tr -s ' ' | cut -d ' ' -f2"`
exist_port_2=`ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu  "ps acux | grep $username | grep python | tr -s ' ' | cut -d ' ' -f2"`
if [[ $exist_port ]]
then
	ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu kill -9 $exist_port 
fi
if [[ $exist_port_2 ]]
then
	ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu kill -9 $exist_port_2 
fi

for i in "${ec2_servers[@]}"
do
	exist_port=`ssh -i $keyfile $username@$i "ps acux | grep $username | grep httpserver | tr -s ' ' | cut -d ' ' -f2"`
	if [[ $exist_port ]]
	then 
		ssh -i $keyfile $username@$i kill -2 $exist_port 
	fi
done 
